MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "mnetv2_no_fc.pth"
  BACKBONE:
    CONV_BODY: "MOBILENET"
  RPN:
    PRE_NMS_TOP_N_TEST: 300
    POST_NMS_TOP_N_TEST: 300
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    #PREDICTOR: "FastRCNNPredictor"
DATASETS:
  TRAIN: ("multihand_train",)
  TEST: ("multihand_val",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.02
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 90000
